<a href="https://colab.research.google.com/github/Durgaprasadkudupudi/Python500/blob/main/DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DAY1**

In [2]:
import pandas as pd

In [6]:
df=pd.read_csv('/content/sample_data/mnist_train_small.csv')
print(df)
type(df)

       6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
19994  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
19996  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
19997  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
19998  5  0    0    0    0    0    0    0    0    0  ...      0      0      0

       0.584  0.585  0.586  0.587  0.588  0.589  0.590
0          0      0      0      0      0      0      0
1          0      0      0      0      0      0      0
2          0      0      0      0      0      0      0
3          0      0      0      0      0      0      0
4          0      0      0      0      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
19994      0      0      0      0      0      0      0
19995      0      0      0      0      0      0      0
19996      0      0      0      0      0      0      0
19997      0      0      0      0      0      0      0
19998      0      0      0      0      0      0      0

[19999 rows x 785 columns]

pandas.core.frame.DataFrame

In [7]:
df.head()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df.head(12)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.tail()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df.tail(12)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19987,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19988,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19989,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19990,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19991,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19992,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df.shape

(19999, 785)

In [13]:
print(type(df.shape))

<class 'tuple'>

In [14]:
len(df)

19999

In [15]:
df.size
#no.rows*no of coloumns

15699215

In [16]:
print(df.columns)

Index(['6', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.581', '0.582', '0.583', '0.584', '0.585', '0.586', '0.587', '0.588',
       '0.589', '0.590'],
      dtype='object', length=785)

In [17]:
df.columns.to_list()

['6',
 '0',
 '0.1',
 '0.2',
 '0.3',
 '0.4',
 '0.5',
 '0.6',
 '0.7',
 '0.8',
 '0.9',
 '0.10',
 '0.11',
 '0.12',
 '0.13',
 '0.14',
 '0.15',
 '0.16',
 '0.17',
 '0.18',
 '0.19',
 '0.20',
 '0.21',
 '0.22',
 '0.23',
 '0.24',
 '0.25',
 '0.26',
 '0.27',
 '0.28',
 '0.29',
 '0.30',
 '0.31',
 '0.32',
 '0.33',
 '0.34',
 '0.35',
 '0.36',
 '0.37',
 '0.38',
 '0.39',
 '0.40',
 '0.41',
 '0.42',
 '0.43',
 '0.44',
 '0.45',
 '0.46',
 '0.47',
 '0.48',
 '0.49',
 '0.50',
 '0.51',
 '0.52',
 '0.53',
 '0.54',
 '0.55',
 '0.56',
 '0.57',
 '0.58',
 '0.59',
 '0.60',
 '0.61',
 '0.62',
 '0.63',
 '0.64',
 '0.65',
 '0.66',
 '0.67',
 '0.68',
 '0.69',
 '0.70',
 '0.71',
 '0.72',
 '0.73',
 '0.74',
 '0.75',
 '0.76',
 '0.77',
 '0.78',
 '0.79',
 '0.80',
 '0.81',
 '0.82',
 '0.83',
 '0.84',
 '0.85',
 '0.86',
 '0.87',
 '0.88',
 '0.89',
 '0.90',
 '0.91',
 '0.92',
 '0.93',
 '0.94',
 '0.95',
 '0.96',
 '0.97',
 '0.98',
 '0.99',
 '0.100',
 '0.101',
 '0.102',
 '0.103',
 '0.104',
 '0.105',
 '0.106',
 '0.107',
 '0.108',
 '0.109',
 '0.110',
 '0.111',
 '0.112',
 '0.113',
 '0.114',
 '0.115',
 '0.116',
 '0.117',
 '0.118',
 '0.119',
 '0.120',
 '0.121',
 '24',
 '67',
 '67.1',
 '18',
 '0.122',
 '0.123',
 '0.124',
 '0.125',
 '0.126',
 '0.127',
 '0.128',
 '0.129',
 '0.130',
 '0.131',
 '0.132',
 '0.133',
 '0.134',
 '0.135',
 '0.136',
 '0.137',
 '0.138',
 '0.139',
 '0.140',
 '0.141',
 '0.142',
 '0.143',
 '0.144',
 '0.145',
 '131',
 '252',
 '252.1',
 '66',
 '0.146',
 '0.147',
 '0.148',
 '0.149',
 '0.150',
 '0.151',
 '0.152',
 '0.153',
 '0.154',
 '0.155',
 '0.156',
 '0.157',
 '0.158',
 '0.159',
 '0.160',
 '0.161',
 '0.162',
 '0.163',
 '0.164',
 '0.165',
 '0.166',
 '0.167',
 '0.168',
 '159',
 '250',
 '232',
 '30',
 '32',
 '0.169',
 '0.170',
 '0.171',
 '0.172',
 '0.173',
 '0.174',
 '0.175',
 '0.176',
 '0.177',
 '0.178',
 '0.179',
 '0.180',
 '0.181',
 '0.182',
 '0.183',
 '0.184',
 '0.185',
 '0.186',
 '0.187',
 '0.188',
 '0.189',
 '0.190',
 '15',
 '222',
 '252.2',
 '108',
 '0.191',
 '0.192',
 '0.193',
 '0.194',
 '0.195',
 '0.196',
 '0.197',
 '0.198',
 '0.199',
 '0.200',
 '0.201',
 '0.202',
 '0.203',
 '0.204',
 '0.205',
 '0.206',
 '0.207',
 '0.208',
 '0.209',
 '0.210',
 '0.211',
 '0.212',
 '0.213',
 '0.214',
 '147',
 '252.3',
 '183',
 '5',
 '0.215',
 '0.216',
 '0.217',
 '0.218',
 '0.219',
 '0.220',
 '0.221',
 '20',
 '89',
 '89.1',
 '73',
 '0.222',
 '0.223',
 '0.224',
 '0.225',
 '0.226',
 '0.227',
 '0.228',
 '0.229',
 '0.230',
 '0.231',
 '0.232',
 '0.233',
 '48',
 '247',
 '252.4',
 '159.1',
 '0.234',
 '0.235',
 '0.236',
 '0.237',
 '0.238',
 '0.239',
 '0.240',
 '79',
 '236',
 '252.5',
 '252.6',
 '249',
 '198',
 '16',
 '0.241',
 '0.242',
 '0.243',
 '0.244',
 '0.245',
 '0.246',
 '0.247',
 '0.248',
 '0.249',
 '41',
 '193',
 '252.7',
 '199',
 '22',
 '0.250',
 '0.251',
 '0.252',
 '0.253',
 '0.254',
 '12',
 '135',
 '248',
 '252.8',
 '252.9',
 '252.10',
 '252.11',
 '252.12',
 '100',
 '0.255',
 '0.256',
 '0.257',
 '0.258',
 '0.259',
 '0.260',
 '0.261',
 '0.262',
 '0.263',
 '100.1',
 '252.13',
 '252.14',
 '88',
 '0.264',
 '0.265',
 '0.266',
 '0.267',
 '0.268',
 '11',
 '171',
 '252.15',
 '252.16',
 '235',
 '175',
 '178',
 '252.17',
 '252.18',
 '224',
 '0.269',
 '0.270',
 '0.271',
 '0.272',
 '0.273',
 '0.274',
 '0.275',
 '0.276',
 '15.1',
 '209',
 '252.19',
 '233',
 '12.1',
 '0.277',
 '0.278',
 '0.279',
 '0.280',
 '49',
 '177',
 '252.20',
 '252.21',
 '89.2',
 '26',
 '0.281',
 '2',
 '166',
 '252.22',
 '252.23',
 '0.282',
 '0.283',
 '0.284',
 '0.285',
 '0.286',
 '0.287',
 '0.288',
 '0.289',
 '96',
 '253',
 '253.1',
 '59',
 '0.290',
 '0.291',
 '0.292',
 '0.293',
 '11.1',
 '177.1',
 '255',
 '253.2',
 '92',
 '0.294',
 '0.295',
 '0.296',
 '0.297',
 '155',
 '253.3',
 '128',
 '0.298',
 '0.299',
 '0.300',
 '0.301',
 '0.302',
 '0.303',
 '0.304',
 '0.305',
 '143',
 '252.24',
 '252.25',
 '10',
 '0.306',
 '0.307',
 '0.308',
 '12.2',
 '171.1',
 '252.26',
 '216',
 '110',
 '13',
 '0.309',
 '0.310',
 '0.311',
 '3',
 '180',
 '232.1',
 '24.1',
 '0.312',
 '0.313',
 '0.314',
 '0.315',
 '0.316',
 '0.317',
 '0.318',
 '0.319',
 '143.1',
 '252.27',
 '170',
 '2.1',
 '0.320',
 '0.321',
 '0.322',
 '135.1',
 '252.28',
 '209.1',
 '19',
 '0.323',
 '0.324',
 '0.325',
 '0.326',
 '0.327',
 '12.3',
 '252.29',
 '132',
 '0.328',
 '0.329',
 '0.330',
 '0.331',
 '0.332',
 '0.333',
 '0.334',
 '0.335',
 '0.336',
 '249.1',
 '252.30',
 '96.1',
 '0.337',
 '0.338',
 '0.339',
 '21',
 '248.1',
 '246',
 '34',
 '0.340',
 '0.341',
 '0.342',
 '0.343',
 '5.1',
 '61',
 '234',
 '152',
 '3.1',
 '0.344',
 '0.345',
 '0.346',
 '0.347',
 '0.348',
 '0.349',
 '0.350',
 '0.351',
 '0.352',
 '253.4',
 '252.31',
 '44',
 '0.353',
 '0.354',
 '0.355',
 '145',
 '252.32',
 '104',
 '0.356',
 '0.357',
 '0.358',
 '46',
 '114',
 '184',
 '252.33',
 '149',
 '34.1',
 '0.359',
 '0.360',
 '0.361',
 '0.362',
 '0.363',
 '0.364',
 '0.365',
 '0.366',
 '0.367',
 '0.368',
 '253.5',
 '252.34',
 '82',
 '0.369',
 '0.370',
 '31',
 '239',
 '252.35',
 '66.1',
 '39',
 '89.3',
 '165',
 '243',
 '252.36',
 '233.1',
 '126',
 '5.2',
 '0.371',
 '0.372',
 '0.373',
 '0.374',
 '0.375',
 '0.376',
 '0.377',
 '0.378',
 '0.379',
 '0.380',
 '0.381',
 '249.2',
 '252.37',
 '244',
 '126.1',
 '98',
 '143.2',
 '252.38',
 '252.39',
 '237',
 '240',
 '253.6',
 '252.40',
 '243.1',
 '174',
 '17',
 '0.382',
 '0.383',
 '0.384',
 '0.385',
 '0.386',
 '0.387',
 '0.388',
 '0.389',
 '0.390',
 '0.391',
 '0.392',
 '0.393',
 '0.394',
 '119',
 '239.1',
 '252.41',
 '252.42',
 '252.43',
 '252.44',
 '252.45',
 '252.46',
 '252.47',
 '252.48',
 '228',
 '179',
 '17.1',
 '0.395',
 '0.396',
 '0.397',
 '0.398',
 '0.399',
 '0.400',
 '0.401',
 '0.402',
 '0.403',
 '0.404',
 '0.405',
 '0.406',
 '0.407',
 '0.408',
 '0.409',
 '0.410',
 '46.1',
 '66.2',
 '66.3',
 '66.4',
 '66.5',
 '66.6',
 '66.7',
 '66.8',
 '66.9',
 '29',
 '0.411',
 '0.412',
 '0.413',
 '0.414',
 '0.415',
 '0.416',
 '0.417',
 '0.418',
 '0.419',
 '0.420',
 '0.421',
 '0.422',
 '0.423',
 '0.424',
 '0.425',
 '0.426',
 '0.427',
 '0.428',
 '0.429',
 '0.430',
 '0.431',
 '0.432',
 '0.433',
 '0.434',
 '0.435',
 '0.436',
 '0.437',
 '0.438',
 '0.439',
 '0.440',
 '0.441',
 '0.442',
 '0.443',
 '0.444',
 '0.445',
 '0.446',
 '0.447',
 '0.448',
 '0.449',
 '0.450',
 '0.451',
 '0.452',
 '0.453',
 '0.454',
 '0.455',
 '0.456',
 '0.457',
 '0.458',
 '0.459',
 '0.460',
 '0.461',
 '0.462',
 '0.463',
 '0.464',
 '0.465',
 '0.466',
 '0.467',
 '0.468',
 '0.469',
 '0.470',
 '0.471',
 '0.472',
 '0.473',
 '0.474',
 '0.475',
 '0.476',
 '0.477',
 '0.478',
 '0.479',
 '0.480',
 '0.481',
 '0.482',
 '0.483',
 '0.484',
 '0.485',
 '0.486',
 '0.487',
 '0.488',
 '0.489',
 '0.490',
 '0.491',
 '0.492',
 '0.493',
 '0.494',
 '0.495',
 '0.496',
 '0.497',
 '0.498',
 '0.499',
 '0.500',
 '0.501',
 '0.502',
 '0.503',
 '0.504',
 '0.505',
 '0.506',
 '0.507',
 '0.508',
 '0.509',
 '0.510',
 '0.511',
 '0.512',
 '0.513',
 '0.514',
 '0.515',
 '0.516',
 '0.517',
 '0.518',
 '0.519',
 '0.520',
 '0.521',
 '0.522',
 '0.523',
 '0.524',
 '0.525',
 '0.526',
 '0.527',
 '0.528',
 '0.529',
 '0.530',
 '0.531',
 '0.532',
 '0.533',
 '0.534',
 '0.535',
 '0.536',
 '0.537',
 '0.538',
 '0.539',
 '0.540',
 '0.541',
 '0.542',
 '0.543',
 '0.544',
 '0.545',
 '0.546',
 '0.547',
 '0.548',
 '0.549',
 '0.550',
 '0.551',
 '0.552',
 '0.553',
 '0.554',
 '0.555',
 '0.556',
 '0.557',
 '0.558',
 '0.559',
 '0.560',
 '0.561',
 '0.562',
 '0.563',
 '0.564',
 '0.565',
 '0.566',
 '0.567',
 '0.568',
 '0.569',
 '0.570',
 '0.571',
 '0.572',
 '0.573',
 '0.574',
 '0.575',
 '0.576',
 '0.577',
 '0.578',
 '0.579',
 '0.580',
 '0.581',
 '0.582',
 '0.583',
 '0.584',
 '0.585',
 '0.586',
 '0.587',
 '0.588',
 '0.589',
 '0.590']

In [18]:
df.dtypes

6        int64
0        int64
0.1      int64
0.2      int64
0.3      int64
         ...
0.586    int64
0.587    int64
0.588    int64
0.589    int64
0.590    int64
Length: 785, dtype: object

In [21]:
d=dict(df.dtypes)
d

{'6': dtype('int64'),
 '0': dtype('int64'),
 '0.1': dtype('int64'),
 '0.2': dtype('int64'),
 '0.3': dtype('int64'),
 '0.4': dtype('int64'),
 '0.5': dtype('int64'),
 '0.6': dtype('int64'),
 '0.7': dtype('int64'),
 '0.8': dtype('int64'),
 '0.9': dtype('int64'),
 '0.10': dtype('int64'),
 '0.11': dtype('int64'),
 '0.12': dtype('int64'),
 '0.13': dtype('int64'),
 '0.14': dtype('int64'),
 '0.15': dtype('int64'),
 '0.16': dtype('int64'),
 '0.17': dtype('int64'),
 '0.18': dtype('int64'),
 '0.19': dtype('int64'),
 '0.20': dtype('int64'),
 '0.21': dtype('int64'),
 '0.22': dtype('int64'),
 '0.23': dtype('int64'),
 '0.24': dtype('int64'),
 '0.25': dtype('int64'),
 '0.26': dtype('int64'),
 '0.27': dtype('int64'),
 '0.28': dtype('int64'),
 '0.29': dtype('int64'),
 '0.30': dtype('int64'),
 '0.31': dtype('int64'),
 '0.32': dtype('int64'),
 '0.33': dtype('int64'),
 '0.34': dtype('int64'),
 '0.35': dtype('int64'),
 '0.36': dtype('int64'),
 '0.37': dtype('int64'),
 '0.38': dtype('int64'),
 '0.39': dtype('int64'),
 '0.40': dtype('int64'),
 '0.41': dtype('int64'),
 '0.42': dtype('int64'),
 '0.43': dtype('int64'),
 '0.44': dtype('int64'),
 '0.45': dtype('int64'),
 '0.46': dtype('int64'),
 '0.47': dtype('int64'),
 '0.48': dtype('int64'),
 '0.49': dtype('int64'),
 '0.50': dtype('int64'),
 '0.51': dtype('int64'),
 '0.52': dtype('int64'),
 '0.53': dtype('int64'),
 '0.54': dtype('int64'),
 '0.55': dtype('int64'),
 '0.56': dtype('int64'),
 '0.57': dtype('int64'),
 '0.58': dtype('int64'),
 '0.59': dtype('int64'),
 '0.60': dtype('int64'),
 '0.61': dtype('int64'),
 '0.62': dtype('int64'),
 '0.63': dtype('int64'),
 '0.64': dtype('int64'),
 '0.65': dtype('int64'),
 '0.66': dtype('int64'),
 '0.67': dtype('int64'),
 '0.68': dtype('int64'),
 '0.69': dtype('int64'),
 '0.70': dtype('int64'),
 '0.71': dtype('int64'),
 '0.72': dtype('int64'),
 '0.73': dtype('int64'),
 '0.74': dtype('int64'),
 '0.75': dtype('int64'),
 '0.76': dtype('int64'),
 '0.77': dtype('int64'),
 '0.78': dtype('int64'),
 '0.79': dtype('int64'),
 '0.80': dtype('int64'),
 '0.81': dtype('int64'),
 '0.82': dtype('int64'),
 '0.83': dtype('int64'),
 '0.84': dtype('int64'),
 '0.85': dtype('int64'),
 '0.86': dtype('int64'),
 '0.87': dtype('int64'),
 '0.88': dtype('int64'),
 '0.89': dtype('int64'),
 '0.90': dtype('int64'),
 '0.91': dtype('int64'),
 '0.92': dtype('int64'),
 '0.93': dtype('int64'),
 '0.94': dtype('int64'),
 '0.95': dtype('int64'),
 '0.96': dtype('int64'),
 '0.97': dtype('int64'),
 '0.98': dtype('int64'),
 '0.99': dtype('int64'),
 '0.100': dtype('int64'),
 '0.101': dtype('int64'),
 '0.102': dtype('int64'),
 '0.103': dtype('int64'),
 '0.104': dtype('int64'),
 '0.105': dtype('int64'),
 '0.106': dtype('int64'),
 '0.107': dtype('int64'),
 '0.108': dtype('int64'),
 '0.109': dtype('int64'),
 '0.110': dtype('int64'),
 '0.111': dtype('int64'),
 '0.112': dtype('int64'),
 '0.113': dtype('int64'),
 '0.114': dtype('int64'),
 '0.115': dtype('int64'),
 '0.116': dtype('int64'),
 '0.117': dtype('int64'),
 '0.118': dtype('int64'),
 '0.119': dtype('int64'),
 '0.120': dtype('int64'),
 '0.121': dtype('int64'),
 '24': dtype('int64'),
 '67': dtype('int64'),
 '67.1': dtype('int64'),
 '18': dtype('int64'),
 '0.122': dtype('int64'),
 '0.123': dtype('int64'),
 '0.124': dtype('int64'),
 '0.125': dtype('int64'),
 '0.126': dtype('int64'),
 '0.127': dtype('int64'),
 '0.128': dtype('int64'),
 '0.129': dtype('int64'),
 '0.130': dtype('int64'),
 '0.131': dtype('int64'),
 '0.132': dtype('int64'),
 '0.133': dtype('int64'),
 '0.134': dtype('int64'),
 '0.135': dtype('int64'),
 '0.136': dtype('int64'),
 '0.137': dtype('int64'),
 '0.138': dtype('int64'),
 '0.139': dtype('int64'),
 '0.140': dtype('int64'),
 '0.141': dtype('int64'),
 '0.142': dtype('int64'),
 '0.143': dtype('int64'),
 '0.144': dtype('int64'),
 '0.145': dtype('int64'),
 '131': dtype('int64'),
 '252': dtype('int64'),
 '252.1': dtype('int64'),
 '66': dtype('int64'),
 '0.146': dtype('int64'),
 '0.147': dtype('int64'),
 '0.148': dtype('int64'),
 '0.149': dtype('int64'),
 '0.150': dtype('int64'),
 '0.151': dtype('int64'),
 '0.152': dtype('int64'),
 '0.153': dtype('int64'),
 '0.154': dtype('int64'),
 '0.155': dtype('int64'),
 '0.156': dtype('int64'),
 '0.157': dtype('int64'),
 '0.158': dtype('int64'),
 '0.159': dtype('int64'),
 '0.160': dtype('int64'),
 '0.161': dtype('int64'),
 '0.162': dtype('int64'),
 '0.163': dtype('int64'),
 '0.164': dtype('int64'),
 '0.165': dtype('int64'),
 '0.166': dtype('int64'),
 '0.167': dtype('int64'),
 '0.168': dtype('int64'),
 '159': dtype('int64'),
 '250': dtype('int64'),
 '232': dtype('int64'),
 '30': dtype('int64'),
 '32': dtype('int64'),
 '0.169': dtype('int64'),
 '0.170': dtype('int64'),
 '0.171': dtype('int64'),
 '0.172': dtype('int64'),
 '0.173': dtype('int64'),
 '0.174': dtype('int64'),
 '0.175': dtype('int64'),
 '0.176': dtype('int64'),
 '0.177': dtype('int64'),
 '0.178': dtype('int64'),
 '0.179': dtype('int64'),
 '0.180': dtype('int64'),
 '0.181': dtype('int64'),
 '0.182': dtype('int64'),
 '0.183': dtype('int64'),
 '0.184': dtype('int64'),
 '0.185': dtype('int64'),
 '0.186': dtype('int64'),
 '0.187': dtype('int64'),
 '0.188': dtype('int64'),
 '0.189': dtype('int64'),
 '0.190': dtype('int64'),
 '15': dtype('int64'),
 '222': dtype('int64'),
 '252.2': dtype('int64'),
 '108': dtype('int64'),
 '0.191': dtype('int64'),
 '0.192': dtype('int64'),
 '0.193': dtype('int64'),
 '0.194': dtype('int64'),
 '0.195': dtype('int64'),
 '0.196': dtype('int64'),
 '0.197': dtype('int64'),
 '0.198': dtype('int64'),
 '0.199': dtype('int64'),
 '0.200': dtype('int64'),
 '0.201': dtype('int64'),
 '0.202': dtype('int64'),
 '0.203': dtype('int64'),
 '0.204': dtype('int64'),
 '0.205': dtype('int64'),
 '0.206': dtype('int64'),
 '0.207': dtype('int64'),
 '0.208': dtype('int64'),
 '0.209': dtype('int64'),
 '0.210': dtype('int64'),
 '0.211': dtype('int64'),
 '0.212': dtype('int64'),
 '0.213': dtype('int64'),
 '0.214': dtype('int64'),
 '147': dtype('int64'),
 '252.3': dtype('int64'),
 '183': dtype('int64'),
 '5': dtype('int64'),
 '0.215': dtype('int64'),
 '0.216': dtype('int64'),
 '0.217': dtype('int64'),
 '0.218': dtype('int64'),
 '0.219': dtype('int64'),
 '0.220': dtype('int64'),
 '0.221': dtype('int64'),
 '20': dtype('int64'),
 '89': dtype('int64'),
 '89.1': dtype('int64'),
 '73': dtype('int64'),
 '0.222': dtype('int64'),
 '0.223': dtype('int64'),
 '0.224': dtype('int64'),
 '0.225': dtype('int64'),
 '0.226': dtype('int64'),
 '0.227': dtype('int64'),
 '0.228': dtype('int64'),
 '0.229': dtype('int64'),
 '0.230': dtype('int64'),
 '0.231': dtype('int64'),
 '0.232': dtype('int64'),
 '0.233': dtype('int64'),
 '48': dtype('int64'),
 '247': dtype('int64'),
 '252.4': dtype('int64'),
 '159.1': dtype('int64'),
 '0.234': dtype('int64'),
 '0.235': dtype('int64'),
 '0.236': dtype('int64'),
 '0.237': dtype('int64'),
 '0.238': dtype('int64'),
 '0.239': dtype('int64'),
 '0.240': dtype('int64'),
 '79': dtype('int64'),
 '236': dtype('int64'),
 '252.5': dtype('int64'),
 '252.6': dtype('int64'),
 '249': dtype('int64'),
 '198': dtype('int64'),
 '16': dtype('int64'),
 '0.241': dtype('int64'),
 '0.242': dtype('int64'),
 '0.243': dtype('int64'),
 '0.244': dtype('int64'),
 '0.245': dtype('int64'),
 '0.246': dtype('int64'),
 '0.247': dtype('int64'),
 '0.248': dtype('int64'),
 '0.249': dtype('int64'),
 '41': dtype('int64'),
 '193': dtype('int64'),
 '252.7': dtype('int64'),
 '199': dtype('int64'),
 '22': dtype('int64'),
 '0.250': dtype('int64'),
 '0.251': dtype('int64'),
 '0.252': dtype('int64'),
 '0.253': dtype('int64'),
 '0.254': dtype('int64'),
 '12': dtype('int64'),
 '135': dtype('int64'),
 '248': dtype('int64'),
 '252.8': dtype('int64'),
 '252.9': dtype('int64'),
 '252.10': dtype('int64'),
 '252.11': dtype('int64'),
 '252.12': dtype('int64'),
 '100': dtype('int64'),
 '0.255': dtype('int64'),
 '0.256': dtype('int64'),
 '0.257': dtype('int64'),
 '0.258': dtype('int64'),
 '0.259': dtype('int64'),
 '0.260': dtype('int64'),
 '0.261': dtype('int64'),
 '0.262': dtype('int64'),
 '0.263': dtype('int64'),
 '100.1': dtype('int64'),
 '252.13': dtype('int64'),
 '252.14': dtype('int64'),
 '88': dtype('int64'),
 '0.264': dtype('int64'),
 '0.265': dtype('int64'),
 '0.266': dtype('int64'),
 '0.267': dtype('int64'),
 '0.268': dtype('int64'),
 '11': dtype('int64'),
 '171': dtype('int64'),
 '252.15': dtype('int64'),
 '252.16': dtype('int64'),
 '235': dtype('int64'),
 '175': dtype('int64'),
 '178': dtype('int64'),
 '252.17': dtype('int64'),
 '252.18': dtype('int64'),
 '224': dtype('int64'),
 '0.269': dtype('int64'),
 '0.270': dtype('int64'),
 '0.271': dtype('int64'),
 '0.272': dtype('int64'),
 '0.273': dtype('int64'),
 '0.274': dtype('int64'),
 '0.275': dtype('int64'),
 '0.276': dtype('int64'),
 '15.1': dtype('int64'),
 '209': dtype('int64'),
 '252.19': dtype('int64'),
 '233': dtype('int64'),
 '12.1': dtype('int64'),
 '0.277': dtype('int64'),
 '0.278': dtype('int64'),
 '0.279': dtype('int64'),
 '0.280': dtype('int64'),
 '49': dtype('int64'),
 '177': dtype('int64'),
 '252.20': dtype('int64'),
 '252.21': dtype('int64'),
 '89.2': dtype('int64'),
 '26': dtype('int64'),
 '0.281': dtype('int64'),
 '2': dtype('int64'),
 '166': dtype('int64'),
 '252.22': dtype('int64'),
 '252.23': dtype('int64'),
 '0.282': dtype('int64'),
 '0.283': dtype('int64'),
 '0.284': dtype('int64'),
 '0.285': dtype('int64'),
 '0.286': dtype('int64'),
 '0.287': dtype('int64'),
 '0.288': dtype('int64'),
 '0.289': dtype('int64'),
 '96': dtype('int64'),
 '253': dtype('int64'),
 '253.1': dtype('int64'),
 '59': dtype('int64'),
 '0.290': dtype('int64'),
 '0.291': dtype('int64'),
 '0.292': dtype('int64'),
 '0.293': dtype('int64'),
 '11.1': dtype('int64'),
 '177.1': dtype('int64'),
 '255': dtype('int64'),
 '253.2': dtype('int64'),
 '92': dtype('int64'),
 '0.294': dtype('int64'),
 '0.295': dtype('int64'),
 '0.296': dtype('int64'),
 '0.297': dtype('int64'),
 '155': dtype('int64'),
 '253.3': dtype('int64'),
 '128': dtype('int64'),
 '0.298': dtype('int64'),
 '0.299': dtype('int64'),
 '0.300': dtype('int64'),
 '0.301': dtype('int64'),
 '0.302': dtype('int64'),
 '0.303': dtype('int64'),
 '0.304': dtype('int64'),
 '0.305': dtype('int64'),
 '143': dtype('int64'),
 '252.24': dtype('int64'),
 '252.25': dtype('int64'),
 '10': dtype('int64'),
 '0.306': dtype('int64'),
 '0.307': dtype('int64'),
 '0.308': dtype('int64'),
 '12.2': dtype('int64'),
 '171.1': dtype('int64'),
 '252.26': dtype('int64'),
 '216': dtype('int64'),
 '110': dtype('int64'),
 '13': dtype('int64'),
 '0.309': dtype('int64'),
 '0.310': dtype('int64'),
 '0.311': dtype('int64'),
 '3': dtype('int64'),
 '180': dtype('int64'),
 '232.1': dtype('int64'),
 '24.1': dtype('int64'),
 '0.312': dtype('int64'),
 '0.313': dtype('int64'),
 '0.314': dtype('int64'),
 '0.315': dtype('int64'),
 '0.316': dtype('int64'),
 '0.317': dtype('int64'),
 '0.318': dtype('int64'),
 '0.319': dtype('int64'),
 '143.1': dtype('int64'),
 '252.27': dtype('int64'),
 '170': dtype('int64'),
 '2.1': dtype('int64'),
 '0.320': dtype('int64'),
 '0.321': dtype('int64'),
 '0.322': dtype('int64'),
 '135.1': dtype('int64'),
 '252.28': dtype('int64'),
 '209.1': dtype('int64'),
 '19': dtype('int64'),
 '0.323': dtype('int64'),
 '0.324': dtype('int64'),
 '0.325': dtype('int64'),
 '0.326': dtype('int64'),
 '0.327': dtype('int64'),
 '12.3': dtype('int64'),
 '252.29': dtype('int64'),
 '132': dtype('int64'),
 '0.328': dtype('int64'),
 '0.329': dtype('int64'),
 '0.330': dtype('int64'),
 '0.331': dtype('int64'),
 '0.332': dtype('int64'),
 '0.333': dtype('int64'),
 '0.334': dtype('int64'),
 '0.335': dtype('int64'),
 '0.336': dtype('int64'),
 '249.1': dtype('int64'),
 '252.30': dtype('int64'),
 '96.1': dtype('int64'),
 '0.337': dtype('int64'),
 '0.338': dtype('int64'),
 '0.339': dtype('int64'),
 '21': dtype('int64'),
 '248.1': dtype('int64'),
 '246': dtype('int64'),
 '34': dtype('int64'),
 '0.340': dtype('int64'),
 '0.341': dtype('int64'),
 '0.342': dtype('int64'),
 '0.343': dtype('int64'),
 '5.1': dtype('int64'),
 '61': dtype('int64'),
 '234': dtype('int64'),
 '152': dtype('int64'),
 '3.1': dtype('int64'),
 '0.344': dtype('int64'),
 '0.345': dtype('int64'),
 '0.346': dtype('int64'),
 '0.347': dtype('int64'),
 '0.348': dtype('int64'),
 '0.349': dtype('int64'),
 '0.350': dtype('int64'),
 '0.351': dtype('int64'),
 '0.352': dtype('int64'),
 '253.4': dtype('int64'),
 '252.31': dtype('int64'),
 '44': dtype('int64'),
 '0.353': dtype('int64'),
 '0.354': dtype('int64'),
 '0.355': dtype('int64'),
 '145': dtype('int64'),
 '252.32': dtype('int64'),
 '104': dtype('int64'),
 '0.356': dtype('int64'),
 '0.357': dtype('int64'),
 '0.358': dtype('int64'),
 '46': dtype('int64'),
 '114': dtype('int64'),
 '184': dtype('int64'),
 '252.33': dtype('int64'),
 '149': dtype('int64'),
 '34.1': dtype('int64'),
 '0.359': dtype('int64'),
 '0.360': dtype('int64'),
 '0.361': dtype('int64'),
 '0.362': dtype('int64'),
 '0.363': dtype('int64'),
 '0.364': dtype('int64'),
 '0.365': dtype('int64'),
 '0.366': dtype('int64'),
 '0.367': dtype('int64'),
 '0.368': dtype('int64'),
 '253.5': dtype('int64'),
 '252.34': dtype('int64'),
 '82': dtype('int64'),
 '0.369': dtype('int64'),
 '0.370': dtype('int64'),
 '31': dtype('int64'),
 '239': dtype('int64'),
 '252.35': dtype('int64'),
 '66.1': dtype('int64'),
 '39': dtype('int64'),
 '89.3': dtype('int64'),
 '165': dtype('int64'),
 '243': dtype('int64'),
 '252.36': dtype('int64'),
 '233.1': dtype('int64'),
 '126': dtype('int64'),
 '5.2': dtype('int64'),
 '0.371': dtype('int64'),
 '0.372': dtype('int64'),
 '0.373': dtype('int64'),
 '0.374': dtype('int64'),
 '0.375': dtype('int64'),
 '0.376': dtype('int64'),
 '0.377': dtype('int64'),
 '0.378': dtype('int64'),
 '0.379': dtype('int64'),
 '0.380': dtype('int64'),
 '0.381': dtype('int64'),
 '249.2': dtype('int64'),
 '252.37': dtype('int64'),
 '244': dtype('int64'),
 '126.1': dtype('int64'),
 '98': dtype('int64'),
 '143.2': dtype('int64'),
 '252.38': dtype('int64'),
 '252.39': dtype('int64'),
 '237': dtype('int64'),
 '240': dtype('int64'),
 '253.6': dtype('int64'),
 '252.40': dtype('int64'),
 '243.1': dtype('int64'),
 '174': dtype('int64'),
 '17': dtype('int64'),
 '0.382': dtype('int64'),
 '0.383': dtype('int64'),
 '0.384': dtype('int64'),
 '0.385': dtype('int64'),
 '0.386': dtype('int64'),
 '0.387': dtype('int64'),
 '0.388': dtype('int64'),
 '0.389': dtype('int64'),
 '0.390': dtype('int64'),
 '0.391': dtype('int64'),
 '0.392': dtype('int64'),
 '0.393': dtype('int64'),
 '0.394': dtype('int64'),
 '119': dtype('int64'),
 '239.1': dtype('int64'),
 '252.41': dtype('int64'),
 '252.42': dtype('int64'),
 '252.43': dtype('int64'),
 '252.44': dtype('int64'),
 '252.45': dtype('int64'),
 '252.46': dtype('int64'),
 '252.47': dtype('int64'),
 '252.48': dtype('int64'),
 '228': dtype('int64'),
 '179': dtype('int64'),
 '17.1': dtype('int64'),
 '0.395': dtype('int64'),
 '0.396': dtype('int64'),
 '0.397': dtype('int64'),
 '0.398': dtype('int64'),
 '0.399': dtype('int64'),
 '0.400': dtype('int64'),
 '0.401': dtype('int64'),
 '0.402': dtype('int64'),
 '0.403': dtype('int64'),
 '0.404': dtype('int64'),
 '0.405': dtype('int64'),
 '0.406': dtype('int64'),
 '0.407': dtype('int64'),
 '0.408': dtype('int64'),
 '0.409': dtype('int64'),
 '0.410': dtype('int64'),
 '46.1': dtype('int64'),
 '66.2': dtype('int64'),
 '66.3': dtype('int64'),
 '66.4': dtype('int64'),
 '66.5': dtype('int64'),
 '66.6': dtype('int64'),
 '66.7': dtype('int64'),
 '66.8': dtype('int64'),
 '66.9': dtype('int64'),
 '29': dtype('int64'),
 '0.411': dtype('int64'),
 '0.412': dtype('int64'),
 '0.413': dtype('int64'),
 '0.414': dtype('int64'),
 '0.415': dtype('int64'),
 '0.416': dtype('int64'),
 '0.417': dtype('int64'),
 '0.418': dtype('int64'),
 '0.419': dtype('int64'),
 '0.420': dtype('int64'),
 '0.421': dtype('int64'),
 '0.422': dtype('int64'),
 '0.423': dtype('int64'),
 '0.424': dtype('int64'),
 '0.425': dtype('int64'),
 '0.426': dtype('int64'),
 '0.427': dtype('int64'),
 '0.428': dtype('int64'),
 '0.429': dtype('int64'),
 '0.430': dtype('int64'),
 '0.431': dtype('int64'),
 '0.432': dtype('int64'),
 '0.433': dtype('int64'),
 '0.434': dtype('int64'),
 '0.435': dtype('int64'),
 '0.436': dtype('int64'),
 '0.437': dtype('int64'),
 '0.438': dtype('int64'),
 '0.439': dtype('int64'),
 '0.440': dtype('int64'),
 '0.441': dtype('int64'),
 '0.442': dtype('int64'),
 '0.443': dtype('int64'),
 '0.444': dtype('int64'),
 '0.445': dtype('int64'),
 '0.446': dtype('int64'),
 '0.447': dtype('int64'),
 '0.448': dtype('int64'),
 '0.449': dtype('int64'),
 '0.450': dtype('int64'),
 '0.451': dtype('int64'),
 '0.452': dtype('int64'),
 '0.453': dtype('int64'),
 '0.454': dtype('int64'),
 '0.455': dtype('int64'),
 '0.456': dtype('int64'),
 '0.457': dtype('int64'),
 '0.458': dtype('int64'),
 '0.459': dtype('int64'),
 '0.460': dtype('int64'),
 '0.461': dtype('int64'),
 '0.462': dtype('int64'),
 '0.463': dtype('int64'),
 '0.464': dtype('int64'),
 '0.465': dtype('int64'),
 '0.466': dtype('int64'),
 '0.467': dtype('int64'),
 '0.468': dtype('int64'),
 '0.469': dtype('int64'),
 '0.470': dtype('int64'),
 '0.471': dtype('int64'),
 '0.472': dtype('int64'),
 '0.473': dtype('int64'),
 '0.474': dtype('int64'),
 '0.475': dtype('int64'),
 '0.476': dtype('int64'),
 '0.477': dtype('int64'),
 '0.478': dtype('int64'),
 '0.479': dtype('int64'),
 '0.480': dtype('int64'),
 '0.481': dtype('int64'),
 '0.482': dtype('int64'),
 '0.483': dtype('int64'),
 '0.484': dtype('int64'),
 '0.485': dtype('int64'),
 '0.486': dtype('int64'),
 '0.487': dtype('int64'),
 '0.488': dtype('int64'),
 '0.489': dtype('int64'),
 '0.490': dtype('int64'),
 '0.491': dtype('int64'),
 '0.492': dtype('int64'),
 '0.493': dtype('int64'),
 '0.494': dtype('int64'),
 '0.495': dtype('int64'),
 '0.496': dtype('int64'),
 '0.497': dtype('int64'),
 '0.498': dtype('int64'),
 '0.499': dtype('int64'),
 '0.500': dtype('int64'),
 '0.501': dtype('int64'),
 '0.502': dtype('int64'),
 '0.503': dtype('int64'),
 '0.504': dtype('int64'),
 '0.505': dtype('int64'),
 '0.506': dtype('int64'),
 '0.507': dtype('int64'),
 '0.508': dtype('int64'),
 '0.509': dtype('int64'),
 '0.510': dtype('int64'),
 '0.511': dtype('int64'),
 '0.512': dtype('int64'),
 '0.513': dtype('int64'),
 '0.514': dtype('int64'),
 '0.515': dtype('int64'),
 '0.516': dtype('int64'),
 '0.517': dtype('int64'),
 '0.518': dtype('int64'),
 '0.519': dtype('int64'),
 '0.520': dtype('int64'),
 '0.521': dtype('int64'),
 '0.522': dtype('int64'),
 '0.523': dtype('int64'),
 '0.524': dtype('int64'),
 '0.525': dtype('int64'),
 '0.526': dtype('int64'),
 '0.527': dtype('int64'),
 '0.528': dtype('int64'),
 '0.529': dtype('int64'),
 '0.530': dtype('int64'),
 '0.531': dtype('int64'),
 '0.532': dtype('int64'),
 '0.533': dtype('int64'),
 '0.534': dtype('int64'),
 '0.535': dtype('int64'),
 '0.536': dtype('int64'),
 '0.537': dtype('int64'),
 '0.538': dtype('int64'),
 '0.539': dtype('int64'),
 '0.540': dtype('int64'),
 '0.541': dtype('int64'),
 '0.542': dtype('int64'),
 '0.543': dtype('int64'),
 '0.544': dtype('int64'),
 '0.545': dtype('int64'),
 '0.546': dtype('int64'),
 '0.547': dtype('int64'),
 '0.548': dtype('int64'),
 '0.549': dtype('int64'),
 '0.550': dtype('int64'),
 '0.551': dtype('int64'),
 '0.552': dtype('int64'),
 '0.553': dtype('int64'),
 '0.554': dtype('int64'),
 '0.555': dtype('int64'),
 '0.556': dtype('int64'),
 '0.557': dtype('int64'),
 '0.558': dtype('int64'),
 '0.559': dtype('int64'),
 '0.560': dtype('int64'),
 '0.561': dtype('int64'),
 '0.562': dtype('int64'),
 '0.563': dtype('int64'),
 '0.564': dtype('int64'),
 '0.565': dtype('int64'),
 '0.566': dtype('int64'),
 '0.567': dtype('int64'),
 '0.568': dtype('int64'),
 '0.569': dtype('int64'),
 '0.570': dtype('int64'),
 '0.571': dtype('int64'),
 '0.572': dtype('int64'),
 '0.573': dtype('int64'),
 '0.574': dtype('int64'),
 '0.575': dtype('int64'),
 '0.576': dtype('int64'),
 '0.577': dtype('int64'),
 '0.578': dtype('int64'),
 '0.579': dtype('int64'),
 '0.580': dtype('int64'),
 '0.581': dtype('int64'),
 '0.582': dtype('int64'),
 '0.583': dtype('int64'),
 '0.584': dtype('int64'),
 '0.585': dtype('int64'),
 '0.586': dtype('int64'),
 '0.587': dtype('int64'),

In [23]:
for i in d:
  if d[i]=='object':
    print(i)

In [25]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [26]:
df.select_dtypes(exclude='object').columns

Index(['6', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.581', '0.582', '0.583', '0.584', '0.585', '0.586', '0.587', '0.588',
       '0.589', '0.590'],
      dtype='object', length=785)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Columns: 785 entries, 6 to 0.590
dtypes: int64(785)
memory usage: 119.8 MB

In [29]:
df.isna().sum()

6        0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.586    0
0.587    0
0.588    0
0.589    0
0.590    0
Length: 785, dtype: int64

In [30]:
df.isnull().sum()

6        0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.586    0
0.587    0
0.588    0
0.589    0
0.590    0
Length: 785, dtype: int64

In [ ]:


# This code performs basic inspection of a pandas DataFrame.

# Read the CSV file into a DataFrame
# df = pd.read_csv('/content/sample_data/mnist_train_small.csv') # This line is already present in the provided code

# Print the entire DataFrame (can be very large for big files)
# print(df)  # This line is already present in the provided code

# Check the data type of the DataFrame
# type(df) # This line is already present in the provided code

# View the first few rows of the DataFrame
# df.head()  # This line is already present in the provided code
# df.head(12)  # This line is already present in the provided code

# View the last few rows
# df.tail()  # This line is already present in the provided code
# df.tail(12) # This line is already present in the provided code

# Get the dimensions of the DataFrame (rows, columns)
# df.shape  # This line is already present in the provided code
# print(type(df.shape)) # This line is already present in the provided code

# Get the number of rows in the DataFrame (equivalent to df.shape[0])
# len(df)  # This line is already present in the provided code

# Total number of elements in the DataFrame (rows * columns)
# df.size  # This line is already present in the provided code

# Get the column names
# print(df.columns)  # This line is already present in the provided code
# df.columns.to_list()  # This line is already present in the provided code

# Get the data types of each column
# df.dtypes  # This line is already present in the provided code

# Create a dictionary of column names and their data types
# d = dict(df.dtypes) # This line is already present in the provided code
# d # This line is already present in the provided code

# Find and print columns with 'object' data type
# for i in d:
#   if d[i]=='object':
#     print(i) # This line is already present in the provided code

# Select columns with 'object' data type
# df.select_dtypes(include='object').columns  # This line is already present in the provided code

# Select columns excluding those with 'object' data type
# df.select_dtypes(exclude='object').columns  # This line is already present in the provided code

# Concise summary of the DataFrame, including data types and non-null values
# df.info() # This line is already present in the provided code

# Calculate the number of missing values in each column (NaN or Null)
# df.isna().sum() # This line is already present in the provided code
# df.isnull().sum()  # This line is already present in the provided code

# **DAY_2**

# "- Check for missing values using df.isnull().
#  - Handle missing data: df.fillna(), df.dropna().
#  - Handle incorrect data types with .astype()."

In [31]:
import pandas as pd

In [35]:
data=pd.read_csv('/content/Bengaluru_House_Data.csv')

In [36]:
data.shape

(13320, 9)

In [37]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [38]:
data.isna().sum().sum()

6201

# filling Null values

In [40]:
df2=data.fillna(value=0)
df2

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,0,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,0,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,0,3600,5.0,0.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,0,550,1.0,1.0,17.00

In [41]:
df2.isnull().sum().sum()

0

In [42]:
df3=data.fillna(value=5)
df3

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,5,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,5,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,5,3600,5.0,5.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,5,550,1.0,1.0,17.00

# filling null values with the previous value

In [43]:
df3=data.fillna(method='pad')
df3

<ipython-input-43-e04c76d107ba>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3=data.fillna(method='pad')

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,Theanmp,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,Soiewre,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,ArsiaEx,3600,5.0,0.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,SollyCl,550,1.0,1.0,17.00

In [44]:
df3.isnull().sum().sum()

0

In [45]:
#filling null value with the next value
df4=data.fillna(method='bfill')
df4

<ipython-input-45-c0b247eebba8>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df4=data.fillna(method='bfill')

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,Soiewre,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,DuenaTa,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,Mahla T,3600,5.0,1.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [46]:
#filling null values with beside colomn value
df5=data.fillna(method='pad', axis=1)
df5

<ipython-input-46-d49d75e182d8>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df5=data.fillna(method='pad', axis=1)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,3 BHK,1440,2.0,3.0,62.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,2 BHK,1200,2.0,1.0,51.0
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,4 BHK,3600,5.0,5.0,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,1 BHK,550,1.0,1.0,17.0

In [47]:
#filling null values with beside colomn value
df6=data.fillna(method='bfill', axis=1)
df6

<ipython-input-47-0bea6f1c4233>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6=data.fillna(method='bfill', axis=1)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,1440,2.0,3.0,62.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,1200,2.0,1.0,51.0
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,3600,5.0,400.0,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,550,1.0,1.0,17.0

In [48]:
#filling  different values in null in different  coloumns
df7=data.fillna({'society':'abcd', 'balcony':'xyz'})
df7

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,abcd,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,abcd,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,abcd,3600,5.0,xyz,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,abcd,550,1.0,1.0,17.00

In [49]:
#filling null values with the mean of a coloumn

df8=data.fillna(value=data['balcony'].mean())
df8

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.000000,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.000000,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1.584376,1440,2.0,3.000000,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.000000,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1.584376,1200,2.0,1.000000,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.000000,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,1.584376,3600,5.0,1.584376,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.000000,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.000000,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,1.584376,550,1.0,1.000000,17.00

In [50]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [51]:
df9=data.dropna()
df9

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00
...,...,...,...,...,...,...,...,...,...
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [52]:
df10=data.dropna(how='all')
#delete the row if the entire row is nan
df10

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [53]:
df11=data.dropna(how='any')
#delete the row if the entire row contain atleast one nan
df11

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00
...,...,...,...,...,...,...,...,...,...
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

# Replace method

In [54]:
import numpy as np
df12=data.replace(to_replace=np.nan, value=1234)
df12

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1234,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1234,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,1234,3600,5.0,1234.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,1234,550,1.0,1.0,17.00

# Interpolate()

In [58]:
data=pd.read_csv('/content/Bengaluru_House_Data.csv')
data['balcony']=data['balcony'].interpolate(method='linear')
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,0.5,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [59]:
data=pd.read_csv('/content/Bengaluru_House_Data.csv')
data['balcony']=data['balcony'].interpolate(method='linear', limit_direction='forward')

data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,0.5,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [8]:
X=24
Y=45
Z=15
ftime=X*Y
if X>3:
  count=0
  total=0
  for j in range(1,X,3):
    count+=1

total=ftime+count*Z
print(count*15)
print(ftime)
print(total)

120
1080
1200

In [9]:
print(1185-1200)

-15

In [10]:
a=((8*15)+(24*45))
print(a)

1200

# Day3

Renaming columns

In [8]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Bengaluru_House_Data.csv')

# Rename columns
df.rename(columns={'total_sqft': 'total_area', 'price': 'house_price'}, inplace=True)

print(df.head())

              area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK

   society total_area  bath  balcony  house_price
0  Coomee        1056   2.0      1.0        39.07
1  Theanmp       2600   5.0      3.0       120.00
2      NaN       1440   2.0      3.0        62.00
3  Soiewre       1521   3.0      1.0        95.00
4      NaN       1200   2.0      1.0        51.00

# Dropping Unnecessary Columns

---

In [9]:
# Drop columns
df.drop(columns=['society', 'availability'], inplace=True)

print(df.head())

              area_type                  location       size total_area  bath  \
0  Super built-up  Area  Electronic City Phase II      2 BHK       1056   2.0
1            Plot  Area          Chikka Tirupathi  4 Bedroom       2600   5.0
2        Built-up  Area               Uttarahalli      3 BHK       1440   2.0
3  Super built-up  Area        Lingadheeranahalli      3 BHK       1521   3.0
4  Super built-up  Area                  Kothanur      2 BHK       1200   2.0

   balcony  house_price
0      1.0        39.07
1      3.0       120.00
2      3.0        62.00
3      1.0        95.00
4      1.0        51.00

# 3. Adding a New Column
Example: Add a new column price_per_sqft calculated as price / total_sqft

---

In [12]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Bengaluru_House_Data.csv')

# Function to clean and convert total_sqft values
def convert_sqft(value):
    value = str(value).strip()
    if '-' in value:
        # Take the average of the range
        parts = value.split('-')
        return (float(parts[0]) + float(parts[1])) / 2
    elif value.replace('.', '', 1).isdigit():
        # If it's a number, convert to float
        return float(value)
    else:
        # Handle cases with 'Sq. Meter', 'Acres', etc.
        numeric_part = ''.join(filter(str.isdigit, value))
        return float(numeric_part) if numeric_part else None

# Apply the function to the total_sqft column
df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

# Drop rows where conversion failed
df.dropna(subset=['total_sqft'], inplace=True)

# Convert price column to numeric
df['price'] = pd.to_numeric(df['price'], errors='coerce')

# Add new column: price per sqft
df['price_per_sqft'] = df['price'] / df['total_sqft']

print(df.head())

              area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK

   society  total_sqft  bath  balcony   price  price_per_sqft
0  Coomee       1056.0   2.0      1.0   39.07        0.036998
1  Theanmp      2600.0   5.0      3.0  120.00        0.046154
2      NaN      1440.0   2.0      3.0   62.00        0.043056
3  Soiewre      1521.0   3.0      1.0   95.00        0.062459
4      NaN      1200.0   2.0      1.0   51.00        0.042500

# Pivoting using pivot function
DAY4
---

In [14]:
import pandas as pd

# Sample data
data = {
    'area_type': ['Super built-up  Area', 'Plot  Area', 'Built-up  Area', 'Plot  Area'],
    'location': ['Whitefield', 'Indiranagar', 'Marathahalli', 'Electronic City'],
    'total_sqft': [1200, 1500, 1100, 1600],
    'bath': [2, 3, 2, 4],
    'price': [6000000, 7500000, 5000000, 8000000]
}

df = pd.DataFrame(data)

# Pivot table: Set location as index and area_type as columns, filling values with price
df_pivot = df.pivot(index='location', columns='area_type', values='price')

print(df_pivot)

area_type        Built-up  Area  Plot  Area  Super built-up  Area
location
Electronic City             NaN   8000000.0                   NaN
Indiranagar                 NaN   7500000.0                   NaN
Marathahalli          5000000.0         NaN                   NaN
Whitefield                  NaN         NaN             6000000.0

In [15]:
# Melting the columns 'price' and 'total_sqft'
df_melted = df.melt(id_vars=['location', 'area_type'], value_vars=['price', 'total_sqft'],
                    var_name='Metric', value_name='Value')

print(df_melted)

          location             area_type      Metric    Value
0       Whitefield  Super built-up  Area       price  6000000
1      Indiranagar            Plot  Area       price  7500000
2     Marathahalli        Built-up  Area       price  5000000
3  Electronic City            Plot  Area       price  8000000
4       Whitefield  Super built-up  Area  total_sqft     1200
5      Indiranagar            Plot  Area  total_sqft     1500
6     Marathahalli        Built-up  Area  total_sqft     1100
7  Electronic City            Plot  Area  total_sqft     1600